# Generated by Django 3.2.4 on 2021-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('address_psc', models.IntegerField(blank=True, null=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('identity', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
