# Generated by Django 3.2.4 on 2021-07-07 13:07

import django.core.validators
from django.db import migrations, models
import kamenice_django.validators.guest


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('address_psc', models.IntegerField(blank=True, null=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=10, null=True, validators=[kamenice_django.validators.guest.validate_citizenship])),
                ('email', models.EmailField(error_messages={'blank': 'E-Mail je povinný údaj', 'invalid': 'Zadejte platnou e-mailovou adresu', 'null': 'E-Mail je povinný údaj'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], error_messages={'invalid_choice': 'Vyberte údaj "Pohlaví" ze seznamu'}, max_length=10, null=True, validators=[kamenice_django.validators.guest.validate_gender])),
                ('identity', models.CharField(error_messages={'blank': 'Číslo občanského průkazu je povinný údaj', 'null': 'Číslo občanského průkazu je povinný údaj'}, max_length=50)),
                ('name', models.CharField(error_messages={'blank': 'Jméno je povinný údaj', 'null': 'Jméno je povinný údaj'}, max_length=100)),
                ('phone_number', models.CharField(error_messages={'blank': 'Telefonní číslo je povinný údaj', 'null': 'Telefonní číslo je povinný údaj'}, max_length=50)),
                ('surname', models.CharField(error_messages={'blank': 'Příjmení je povinný údaj', 'null': 'Příjmení je povinný údaj'}, max_length=100)),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
