# Generated by Django 3.2.4 on 2021-07-19 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.CharField(choices=[('CHILD', 'Do 3 let'), ('YOUNG', '3-12 let'), ('ADULT', '12+')], error_messages={'blank': 'Vyberte věk ze seznamu', 'invalid_choice': 'Vyberte věk ze seznamu', 'null': 'Vyberte věk ze seznamu'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(error_messages={'blank': 'E-Mail je povinný údaj', 'invalid': 'Zadejte platnou e-mailovou adresu', 'null': 'E-Mail je povinný údaj', 'unique': 'Uživatel s tímto e-mailem již existuje'}, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
