# Generated by Django 3.2.4 on 2021-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='price_breakfast_child',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='price_halfboard_child',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='discountsuite',
            name='type',
            field=models.CharField(choices=[('CHILD_DISCOUNT', 'Child 3-12 years old'), ('EXTRA_BED_DISCOUNT', 'Extra bed'), ('FIFTH_MORE_BED', 'Fifth and more bed'), ('INFANT_DISCOUNT', 'Child up to 3 years old'), ('THIRD_FOURTH_BED', 'Third and forth bed'), ('THREE_NIGHTS_DISCOUNT', 'Three or more nights')], error_messages={'invalid_choice': 'Select discount type from the list', 'null': 'Select discount type from the list'}, max_length=100),
        ),
    ]
