# Generated by Django 3.2.4 on 2021-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired',
            field=models.DateTimeField(blank=True, error_messages={'invalid': 'Enter valid date for the expiration'}, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.CharField(blank=True, choices=[('INFANT', 'Up to 3 years'), ('CHILD', '3-12 years'), ('YOUNG', '12+ years'), ('ADULT', 'Adult')], error_messages={'invalid_choice': 'Choose age from the list'}, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roommate',
            name='age',
            field=models.CharField(blank=True, choices=[('INFANT', 'Up to 3 years'), ('CHILD', '3-12 years'), ('YOUNG', '12+ years'), ('ADULT', 'Adult')], error_messages={'invalid_choice': 'Choose age from the list'}, max_length=10, null=True),
        ),
    ]
