# Generated by Django 3.2.4 on 2021-11-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211117_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountSettings',
        ),
    ]
