# Generated by Django 3.2.4 on 2021-10-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price_extra',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='price_child',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='price_extra',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='price_infant',
        ),
        migrations.AddField(
            model_name='suite',
            name='number_beds_extra',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.CharField(blank=True, choices=[('INFANT', 'Child up to 3 years old'), ('CHILD', 'Child 3-12 years old'), ('YOUNG', '12+ years'), ('ADULT', 'Adult')], error_messages={'invalid_choice': 'Choose age from the list'}, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CHILD', 'Child 3-12 years old'), ('EXTRA_BED', 'Extra bed'), ('INFANT', 'Child up to 3 years old'), ('THREE_NIGHTS', 'Three or more nights')], error_messages={'invalid_choice': 'Select discount type from the list', 'null': 'Select discount type from the list'}, max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
