# Generated by Django 3.2.4 on 2021-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210719_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.CharField(blank=True, choices=[('CHILD', 'Do 3 let'), ('YOUNG', '3-12 let'), ('ADULT', '12+')], error_messages={'invalid_choice': 'Vyberte věk ze seznamu'}, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='identity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
