# Generated by Django 3.2.4 on 2021-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210720_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.CharField(blank=True, choices=[('INFANT', 'Do 3 let'), ('CHILD', '3-12 let'), ('YOUNG', '12+'), ('ADULT', 'Dospělý')], error_messages={'invalid_choice': 'Vyberte věk ze seznamu'}, max_length=10, null=True),
        ),
    ]
