# Generated by Django 3.2.4 on 2021-10-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211018_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CHILD_BREAKFAST_DISCOUNT', 'Breakfast (child 3-12 years old)'), ('HALFBOARD_DISCOUNT', 'Halfboard (child 3-12 years old)')], error_messages={'invalid_choice': 'Select discount type from the list', 'null': 'Select discount type from the list'}, max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_discount_settings',
                'default_permissions': (),
                'default_related_name': 'discount_settings_set',
            },
        ),
        migrations.CreateModel(
            name='DiscountSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CHILD_DISCOUNT', 'Child 3-12 years old'), ('EXTRA_BED_DISCOUNT', 'Extra bed'), ('INFANT_DISCOUNT', 'Child up to 3 years old'), ('THREE_NIGHTS_DISCOUNT', 'Three or more nights')], error_messages={'invalid_choice': 'Select discount type from the list', 'null': 'Select discount type from the list'}, max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_suite_set', to='api.suite')),
            ],
            options={
                'db_table': 'api_discount_suite',
                'default_permissions': (),
                'default_related_name': 'discount_suite_set',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('municipality_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('price_breakfast', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('price_halfboard', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_avatar', models.CharField(blank=True, max_length=150, null=True)),
                ('user_color', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='discount',
            name='suite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='discountsettings',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_settings_set', to='api.settings'),
        ),
    ]
