# Generated by Django 3.2.4 on 2021-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_discountsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('drive_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('path_pdf', models.CharField(blank=True, max_length=100, null=True)),
                ('path_docx', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'api_guest_statement',
            },
        ),
    ]
