# Generated by Django 3.2.4 on 2021-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211024_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='municipality_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_breakfast',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_halfboard',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
    ]
