# Generated by Django 3.2.4 on 2022-01-17 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gueststatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price_accommodation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price_meal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price_municipality',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price_total',
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_suites',
            field=models.ManyToManyField(related_name='_api_reservation_extra_suites_+', to='api.Suite'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.suite'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('ACCOMMODATED', 'Currently accommodated'), ('BINDING', 'Binding reservation'), ('INHABITED', 'Occupied term'), ('INQUIRY', 'Inquiry'), ('NONBINDING', 'Non-binding reservation')], error_messages={'invalid_choice': 'Select reservation type from the list', 'null': 'Select reservation type from the list'}, max_length=50),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.DecimalField(decimal_places=2, error_messages={'null': 'Price for accommodation is required field'}, max_digits=10)),
                ('days', models.IntegerField(error_messages={'blank': 'To calculate price, the number of days should be at least 1.', 'min_value': 'To calculate price, the number of days should be at least 1.', 'null': 'To calculate price, the number of days should be at least 1.'}, validators=[django.core.validators.MinValueValidator(1)])),
                ('meal', models.DecimalField(decimal_places=2, error_messages={'null': 'Price for meal is required field'}, max_digits=10)),
                ('municipality', models.DecimalField(decimal_places=2, error_messages={'null': 'Municipality fee is required field'}, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, error_messages={'null': 'Total price is required field'}, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
