# Generated by Django 3.2.4 on 2022-02-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220117_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
