# Generated by Django 3.2.4 on 2021-08-24 15:04

import api.models.Reservation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hash',
            field=models.CharField(blank=True, default=api.models.Reservation.generate_reservation_hash, max_length=10, null=True),
        ),
    ]
