# Generated by Django 3.2.4 on 2022-02-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_roommate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='roommates',
        ),
    ]
