# Generated by Django 3.2.4 on 2021-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210902_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suite',
            name='price_base',
            field=models.DecimalField(decimal_places=2, error_messages={'null': 'Base price is required field'}, max_digits=6),
        ),
        migrations.AlterField(
            model_name='suite',
            name='price_child',
            field=models.DecimalField(decimal_places=2, error_messages={'null': 'Price for child is required field'}, max_digits=6),
        ),
        migrations.AlterField(
            model_name='suite',
            name='price_extra',
            field=models.DecimalField(decimal_places=2, error_messages={'null': 'Price for extra bed is required field'}, max_digits=6),
        ),
        migrations.AlterField(
            model_name='suite',
            name='price_infant',
            field=models.DecimalField(decimal_places=2, error_messages={'null': 'Price for child is required field'}, max_digits=6),
        ),
    ]
