# Generated by Django 3.2.4 on 2021-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_accommodation',
            field=models.DecimalField(decimal_places=2, default=0.0, error_messages={'null': 'Price for accommodation is required field'}, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, error_messages={'null': 'Price for extra bed(s) is required field'}, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_meal',
            field=models.DecimalField(decimal_places=2, default=0.0, error_messages={'null': 'Price for meal is required field'}, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_municipality',
            field=models.DecimalField(decimal_places=2, default=0.0, error_messages={'null': 'Municipality fee is required field'}, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0.0, error_messages={'null': 'Total price is required field'}, max_digits=10),
            preserve_default=False,
        ),
    ]
