AGE_CHOICE_ADULT = 'ADULT'
AGE_CHOICE_CHILD = 'CHILD'
AGE_CHOICE_INFANT = 'INFANT'
AGE_CHOICE_YOUNG = 'YOUNG'

CITIZENSHIP_CZ = 'cze'

DEFAULT_ARRIVAL_TIME = '15:00'
DEFAULT_DEPARTURE_TIME = '10:00'

DISCOUNT_CHOICE_CHILD = 'CHILD_DISCOUNT'
DISCOUNT_CHOICE_EXTRA_BED = 'EXTRA_BED_DISCOUNT'
DISCOUNT_CHOICE_FIFTH_MORE_BED = 'FIFTH_MORE_BED'
DISCOUNT_CHOICE_INFANT = 'INFANT_DISCOUNT'
DISCOUNT_CHOICE_THIRD_FOURTH_BED = 'THIRD_FOURTH_BED'
DISCOUNT_CHOICE_THREE_NIGHTS = 'THREE_NIGHTS_DISCOUNT'

ENVIRON_EMAIL_API_KEY = 'EMAIL_API_KEY'
ENVIRON_EMAIL_CONFIRMATION_TEMPLATE = 'EMAIL_CONFIRMATION_TEMPLATE_ID'
ENVIRON_EMAIL_EXPIRATION_TEMPLATE = 'EMAIL_EXPIRATION_TEMPLATE_ID'
ENVIRON_EMAIL_INQUIRY_TEMPLATE = 'EMAIL_INQUIRY_TEMPLATE_ID'

MEAL_CHOICE_BREAKFAST = 'BREAKFAST'
MEAL_CHOICE_HALFBOARD = 'HALFBOARD'
MEAL_CHOICE_NOMEAL = 'NOMEAL'

MEAL_PRICE_BREAKFAST = 80
MEAL_PRICE_HALFBOARD = 200

RESERVATION_TYPE_ACCOMMODATED = 'ACCOMMODATED'
RESERVATION_TYPE_BINDING = 'BINDING'
RESERVATION_TYPE_INHABITED = 'INHABITED'
RESERVATION_TYPE_INQUIRY = 'INQUIRY'
RESERVATION_TYPE_NONBINDING = 'NONBINDING'
