AGE_CHOICE_ADULT = 'ADULT'
AGE_CHOICE_CHILD = 'CHILD'
AGE_CHOICE_INFANT = 'INFANT'
AGE_CHOICE_YOUNG = 'YOUNG'

DISCOUNT_CHOICE_EXTRA_BED = 'EXTRA_BED'

ENVIRON_EMAIL_API_KEY = 'EMAIL_API_KEY'
ENVIRON_EMAIL_CONFIRMATION_TEMPLATE = 'EMAIL_CONFIRMATION_TEMPLATE_ID'
ENVIRON_EMAIL_EXPIRATION_TEMPLATE = 'EMAIL_EXPIRATION_TEMPLATE_ID'

MEAL_CHOICE_BREAKFAST = 'BREAKFAST'
MEAL_CHOICE_HALFBOARD = 'HALFBOARD'
MEAL_CHOICE_NOMEAL = 'NOMEAL'

RESERVATION_TYPE_ACCOMMODATED = 'ACCOMMODATED'
RESERVATION_TYPE_BINDING = 'BINDING'
RESERVATION_TYPE_INHABITED = 'INHABITED'
RESERVATION_TYPE_NONBINDING = 'NONBINDING'
